name: Create Lambda Layer

on:
  workflow_dispatch:

jobs:
  create_lambda_layer:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: nba-connections
      S3_KEY: dependencies.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2  # Use the same Python version as your virtual environment

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package dependencies
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python
          zip -r9 ${GITHUB_WORKSPACE}/layer.zip python

      - name: Upload layer to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your desired AWS region
      - run: aws s3 cp layer.zip s3://$S3_BUCKET_NAME/$S3_KEY